name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 设置GITHUB_TOKEN的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过正在运行和最新队列之间的运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 删除 package-lock.json 避免版本冲突
      run: rm -f package-lock.json
        
    - name: 安装依赖
      run: |
        npm install
        npm install @rollup/rollup-linux-x64-gnu --save-optional || true
        
    - name: 运行代码检查
      run: npm run lint
      
    - name: 构建项目
      run: |
        npm run build || npm run build:ci
      env:
        NODE_ENV: production
        ROLLUP_USE_NODE: true
        
    - name: 上传构建产物
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 